[0m16:30:57.843633 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa34d393e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa34ba00400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa34ba003a0>]}


============================== 16:30:57.850320 | d4164778-7b00-44cf-b76c-9d9e0b22d5b7 ==============================
[0m16:30:57.850320 [info ] [MainThread]: Running with dbt=1.8.4
[0m16:30:57.851040 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/root/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init my_project', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:30:57.863007 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/root/.dbt')}
[0m16:30:57.863649 [info ] [MainThread]: Creating dbt configuration folder at 
[0m16:30:57.865194 [info ] [MainThread]: A project called my_project already exists here.
[0m16:30:57.869408 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.12937517, "process_user_time": 1.59582, "process_kernel_time": 0.292903, "process_mem_max_rss": "84244", "process_in_blocks": "1400", "process_out_blocks": "8"}
[0m16:30:57.870858 [debug] [MainThread]: Command `dbt init` succeeded at 16:30:57.870581 after 0.13 seconds
[0m16:30:57.871929 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa34d393e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa34b9c4df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa34ba00880>]}
[0m16:30:57.872794 [debug] [MainThread]: Flushing usage events
[0m22:36:36.488530 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbdf8af4df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbdf7154b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbdf7154c10>]}


============================== 22:36:36.501347 | 39eced78-4c73-47d1-a028-e0eca1d7a98e ==============================
[0m22:36:36.501347 [info ] [MainThread]: Running with dbt=1.8.4
[0m22:36:36.502632 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/root/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:36:36.503711 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /root/dbt-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:36:36.505399 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.08695525, "process_user_time": 1.557416, "process_kernel_time": 0.109817, "process_mem_max_rss": "84536", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m22:36:36.506375 [debug] [MainThread]: Command `dbt run` failed at 22:36:36.506226 after 0.09 seconds
[0m22:36:36.506939 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbdf8af4df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbdf7154a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbdf7154af0>]}
[0m22:36:36.507423 [debug] [MainThread]: Flushing usage events
[0m22:38:37.893407 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f302b6bee50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3029d1baf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3029d1bbb0>]}


============================== 22:38:37.903107 | 4968bcba-ac21-4a4c-8f6b-5b207e1f1e67 ==============================
[0m22:38:37.903107 [info ] [MainThread]: Running with dbt=1.8.4
[0m22:38:37.903812 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:38:37.904534 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /root/dbt-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:38:37.905613 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.08021184, "process_user_time": 1.611009, "process_kernel_time": 0.070043, "process_mem_max_rss": "84464", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m22:38:37.906388 [debug] [MainThread]: Command `dbt run` failed at 22:38:37.906249 after 0.08 seconds
[0m22:38:37.906904 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f302b6bee50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3029d1b9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3029d1ba90>]}
[0m22:38:37.907375 [debug] [MainThread]: Flushing usage events
